Created button to assign data role access
Azure-Samples/digital-twins-explorer pull request #80
Opened 2020-12-04 21:45 UTC by alexkarcher-msft

This button shows up when the app receives an auth error from the DT API. This error is primarily caused by users not realizing that they are missing data plane access to their app.

This button gives the user a one click step that assigns them Azure Digital Twins Data Owner access to their app.

![image](https://user-images.githubusercontent.com/22549328/101217857-e69b3f80-3636-11eb-82d9-3356df89e94f.png)
![image](https://user-images.githubusercontent.com/22549328/101217874-ebf88a00-3636-11eb-9a1c-bd15852b88ee.png)
![image](https://user-images.githubusercontent.com/22549328/101217833-dbe0aa80-3636-11eb-9efe-936816fa0a6c.png)

2020-12-07 18:40 UTC, jamescarpinter requested changes
Great feature! A few notes inline and a few general comments:
* Could you please run `npm run lint` and address the style issues? Most are just trivial but it helps keep the code base consistent.
* You might want to consider merging this into the `development` branch. Then we can give it a smoke test before releasing it more generally.
* When the app is deployed to Azure, we drop the NPM-based proxy in favor of an Azure Functions-based proxy. So we'd either need to disable this feature when running in Azure or update the Azure Functions proxy to provide the same functionality.

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +      apiService.addReaderRBAC().then(requestParams =>
We've typically used async/await over explicit promises. Does this approach work better here?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +        auth = <DefaultButton className="modal-button close-button" onClick={this.fixPermissions} style={{width:150}}>Assign yourself data reader access</DefaultButton>;
Our preferred approach has been to centralize layout/content in the render() method rather than passing components via state. We've found this makes it easier to understand what might be rendered in a given scenario. E.g. we'd pass flags here and then create the right components in the render method.

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +          for(var i in requestParams){
I think this use of `var` should be `const` instead?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +import { HttpResponse } from "@microsoft/signalr";
What's this used for?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> -
Can we revert this change?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +    //Get the user's principle ID
I think this should be `principal` (rather than `principle`).

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +    return fetch('http://localhost:3000/api/proxy/Graph/v1.0/me', requestOptions)
If this is an async method, we can probably use `await` rather than `then`?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +    async addReaderRBAC(){
This is a really long method. Maybe consider splitting it up? It might even deserve its own class (as this has traditionally be focused on the DT API).

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +          'x-adt-host': 'graph.microsoft.com'
Is this necessary? If we're using our own `/Graph` sub-path on the proxy?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/setupProxy.js
> -    if (!token || token.expiresOnTimestamp < Date.now()) {
There's a fair amount of repeated code here. Could we create a simple object to represent each of the three pass targets and their respective tokens & scopes? And then simplify the logic a bit?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +              for(let value in result.value){
Would this be better as a for ... of? If result.value is enumerable?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +                //console.log(result.value[value])
We can probably remove commented console log code.

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +                if(typeof result.value[value].name === 'string'){
What scenario are we testing for here? I.e. when would this not be a string?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +      "appName": appAdtUrl.split(".api.")[0].substring(8)
Rather than doing a substring here, it might be better to use `new URL` and explicitly fetch what you need?

2020-12-07 18:40 UTC, jamescarpinter commented on client/src/services/ApiService.js
> +                    "roleDefinitionId": `${requestParams.ARMId}/providers/Microsoft.Authorization/roleDefinitions/bcd981a7-7f74-457b-83e1-cceb9e632ffe`
It might be good to extract the GUID and define it as a constant (so it's clear what it is, i.e. a well-known ID).

2020-12-16 16:43 UTC, alexkarcher-msft commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +      apiService.addReaderRBAC().then(requestParams =>
Can do! Updated the logic in https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/ef301b4c76b9bfe0c520fad6bc872dbe22717acf

2020-12-16 16:50 UTC, alexkarcher-msft commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +        auth = <DefaultButton className="modal-button close-button" onClick={this.fixPermissions} style={{width:150}}>Assign yourself data reader access</DefaultButton>;
That makes sense! I think I got it set up with https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/ce3ddf0b34ff4c96a095da187fc524fb1b11ef5e but I'd love your feedback 😄

2020-12-16 16:51 UTC, alexkarcher-msft commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +          for(var i in requestParams){
Got it!

2020-12-16 16:53 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +import { HttpResponse } from "@microsoft/signalr";
Honestly no idea. It was here before I started. 

It looks like it's been removed from the main repo, so I'll pull it out here too.

2020-12-16 19:34 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +                //console.log(result.value[value])
Done 👍

2021-01-13 17:51 UTC, alexkarcher-msft commented on client/src/components/ErrorMessageComponent/ErrorMessage.js
> +        auth = <DefaultButton className="modal-button close-button" onClick={this.fixPermissions} style={{width:150}}>Assign yourself data reader access</DefaultButton>;
The logic to display the correct response is actually a bit more complicated than I thought. I added everything else necessary in https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/8f17e9aed64da28ecd8adc54fadd0190d7e0aeda

2021-01-13 17:54 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +          'x-adt-host': 'graph.microsoft.com'
Good call out! I've removed all of those headers.

2021-01-13 17:56 UTC, alexkarcher-msft commented on client/src/setupProxy.js
> -    if (!token || token.expiresOnTimestamp < Date.now()) {
Good call. I was struggling a bit with how to make this more eloquent. I've taken a crack at removing the duplicated code here https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/8f17e9aed64da28ecd8adc54fadd0190d7e0aeda#diff-192e648b0be6655f1b1be574c218aad41d832ac3fa4d99ad12a8198beae6b157

2021-01-13 18:07 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +                if(typeof result.value[value].name === 'string'){
When there are no twins instances found we get back "false" and when there are instances we get back an array of instances. I've changed around the logic to do that check earlier. https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/bcc7d50726a6bad9e01a437c9fde35b0f7a36f0c

2021-01-13 18:08 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +    //Get the user's principle ID
Good catch! Fixed in https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/bcc7d50726a6bad9e01a437c9fde35b0f7a36f0c

2021-01-13 18:09 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> -
Done :)

2021-01-13 18:24 UTC, alexkarcher-msft commented
Hi James!

Thanks so much for taking the time to walk through all of these changes with me! I'm learning a ton 😊
I'm chipping away at all of your requests and have a lot of them done. My big rocks left on the table are:

- [ ] Add my API changes to Functions or disable this in Azure
- [ ] Convert function into a class for RBAC functionality
- [ ] Change some (all?) promises to async calls
- [ ] Delete this PR and open a new PR against development branch

I'd love to move this over to a PR against the dev branch as soon as I can so you all can start testing. Do you think we're at that point with the state of changes now?

2021-01-14 00:44 UTC, jamescarpinter commented
Thanks for all the hard work @alexkarcher-msft! Re: next steps, I believe there's a bunch of functionality in develop that is in the final stage of testing before being merged into master. We can definitely look at bringing your changes into develop after that's merged. Typically anything we merge into develop should be ready for merge into master after test sign off (as we prefer not to cherry pick features from develop). So from my perspective, it'd be great to get promises -> async/await and at least disabling this for Azure-based deployments before we merge into develop. We can then address the RBAC class + Azure feature parity after that. Sound OK? Happy to do a quick call if that would help accelerate any of the above.

2021-01-14 00:59 UTC, alexkarcher-msft commented
Sounds perfect to me James! I can get the promises -> async/await change done as I have time in the next few days. Do you happen to know an easy way to tell in code if ADT Explorer is running in Azure?

2021-01-14 03:45 UTC, jamescarpinter commented
Good question! I don't think there is a way of detecting it right now. Perhaps the best option is just to fail gracefully. I.e. add code to Proxy.cs to check for api/proxy/rbac and api/proxy/graph requests and return a 501? Then the client side code could catch the error and show a dialog with the error message plus a comment mentioning this feature is not yet available in Azure.

2021-02-23 02:38 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +    return fetch('http://localhost:3000/api/proxy/Graph/v1.0/me', requestOptions)
Done in https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/b6ac34a3fcb5b3ca7a544d5bfecfff1d78c795db

2021-02-23 02:39 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +    async addReaderRBAC(){
Good call. I split it up and moved it out to it's own class. I can see how everything is now much easier to read :)
https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/c5c318eb2277fec89622db12eb78ab8e90bbba6a

2021-02-23 02:39 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +              for(let value in result.value){
Yep! I am learning A LOT about javascript. Fixed here: https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/76a799359400d47b14b2c6e4177eac3841cfce9d

2021-02-23 02:40 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +      "appName": appAdtUrl.split(".api.")[0].substring(8)
Done here: https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/cc0856912648958849d1e8a69c936cfe7db7ce79

Although, unless you have a secret method for get know a way to get that first subdomain more effectively, it's still using string.split

2021-02-23 02:41 UTC, alexkarcher-msft commented on client/src/services/ApiService.js
> +                    "roleDefinitionId": `${requestParams.ARMId}/providers/Microsoft.Authorization/roleDefinitions/bcd981a7-7f74-457b-83e1-cceb9e632ffe`
Good call! Did that here: https://github.com/Azure-Samples/digital-twins-explorer/pull/80/commits/c5c318eb2277fec89622db12eb78ab8e90bbba6a

2021-02-23 03:12 UTC, alexkarcher-msft commented
I just realized, this whole feature doesn't really make much sense with the Functions proxy. Locally, the user is logged in as someone with owner access to the twins instance. But, in Azure, the Function app doesn't have owner access to the twins instance by default. So, I don't see much point adding the proxy to Functions as well.

My next step is to make sure this fails gracefully and then I'll open a PR against the dev branch

2021-02-23 03:30 UTC, jamescarpinter commented
Completely agree re: cloud-based build. Perhaps the cloud API could be stubbed out to return a 501 not implemented?

And we might like to consider a client-side check to hide or disable the option when not applicable. While it's far from 100% reliable, a check on the serving host name could be a good heuristic?

2021-02-23 04:01 UTC, alexkarcher-msft commented
I added some quick error handling inside of the RBAC method. I was able to test it working in Azure 🤩 

I think I'm all ready for testing this against the dev branch. I'm signing off for the night, but I'll open a PR for you to look over in the morning. Thanks again for all the help and patience walking through this with me!

I've got the whole rest of tomorrow for the hackathon to walk through any feedback 😄

2021-03-31 22:49 UTC, closed without merging